[default]
monitor_speed = 115200
upload_speed = 921600
build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_extra_dirs = ../lib

[env:seeed_xiao_esp32c6]
platform = espressif32
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = ${default.monitor_speed}
upload_speed = ${default.upload_speed}
build_flags = ${default.build_flags}
lib_extra_dirs = ${default.lib_extra_dirs}

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = ${default.monitor_speed}
upload_speed = ${default.upload_speed}
build_flags = ${default.build_flags}
lib_extra_dirs = ${default.lib_extra_dirs}

[env:native]
platform = native
lib_extra_dirs = ${default.lib_extra_dirs}
lib_deps =
    arduino_mock
    protocol
