[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_extra_dirs = ../lib
lib_ignore = arduino_mock

[env:native]
platform = native
lib_extra_dirs = ../lib
lib_deps =
    arduino_mock
    protocol
test_build_src = yes
src_filter = +<*> -<main.cpp> -<RemoteSender.cpp>
lib_ignore = wireless
